logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  datasource:
    url: ${DATABASE_URL_H2:jdbc:h2:mem:vault_db}
    password: ${DATABASE_PASSWORD_H2:Saalik@123}
    username: ${DATABASE_USERNAME_H2:vault}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false